### ISSUE TITLE
'ManifestFactory' object has no attribute 'set_base_metadata_uri'

### ISSUE THREAD

**Issue by tangfucius** [iiif-prezi/iiif-prezi#16]
I tried to run example-factory.py from the example folder, but I got the error above. Inspecting the object shows that the method 'set_base_metadata_uri' doesn't exist. Is the example up to date? I am on Python 3.5.

**Comment by azaroth42** [comment]
@tangfucius Thanks! We changed the API on the factory to use "prezi" instead of "metadata".  So "set_base_prezi_uri" and equivalent methods and properties.  "metadata" was a hold over from a long time ago when the IIIF Presentation API was called a metadata API.

Will fix the examples!

Would be great to hear (here or on iiif-discuss@googlegroups.com) what you're using IIIF for :)
